app:
  scheduler:
    enable: true
    interval: 10s
    force-check-delay: 10s
  basic-urls:
    git-hub-basic-url: https://api.github.com
    stack-overflow-basic-url: https://api.stackexchange.com/2.3
    bot-basic-url: http://localhost:8090

spring:
  application:
    name: scrapper

server:
  port: 8080

springdoc.swagger-ui.path: /swagger-ui

logging:
  config: classpath:log4j2-plain.xml
