app:
  scheduler:
    enable: ${SCRAPPER_APP_SCHEDULER_ENABLE:true}
    interval: ${SCRAPPER_APP_SCHEDULER_INTERVAL:10s}
    force-check-delay: ${SCRAPPER_APP_SCHEDULER_FORCE_CHECK_DELAY:10s}

spring:
  application:
    name: ${SCRAPPER_SPRING_APPLICATION_NAME:scrapper}

server:
  port: ${SCRAPPER_SERVER_PORT:8080}

logging:
  config: ${SCRAPPER_LOGGING_CONFIG:"classpath:log4j2-plain.xml"}
