app:
  telegram-token: ${BOT_TELEGRAM_TOKEN:unset}

spring:
  application:
    name: ${BOT_SPRING_APPLICATION_NAME:bot}
  jackson:
    time-zone: ${BOT_SPRING_JACKSON_TIME_ZONE:UTC}

server:
  port: ${BOT_SERVER_PORT:8090}

logging:
  config: ${BOT_LOGGING_CONFIG:"classpath:log4j2-plain.xml"}
