app:
  telegram-token: ${telegramToken}
  basic-urls:
    scrapper-basic-url: http://localhost:8080

spring:
  application:
    name: bot
  jackson:
    time-zone: UTC

server:
  port: 8090

springdoc.swagger-ui.path: /swagger-ui

logging:
  config: classpath:log4j2-plain.xml
